### ISSUE TITLE
[🐞 Documentation Bug]: Serverless Jobs OpenAPI spec for environment variables

### ISSUE THREAD

**Issue by smndtrl** [scaleway/docs-content#2628]
### What content on scaleway.com/en/docs is affected?

https://www.scaleway.com/en/developers/static/scaleway.serverless_jobs.v1alpha1.Api.yml

### What part(s) of the content would you like to see updated?

The `environment_variables` property on all of the job definitions currently is
```yaml
environment_variables:
  type: object
  properties:
    <environment_variableKey>:
      type: string
  additionalProperties: true
```

This is suboptimal as generators think, that there's a field called `<environment_variableKey>` with a string value.
```json
{ "<environment_variableKey>": "asdf" }
```
would be correct with the spec.
A HashMap/Dictionary is what would be better here - [Swagger](https://swagger.io/docs/specification/data-models/dictionaries/)

I successfully used code generators with the following:

```yaml
environment_variables:
  type: object
  additionalProperties:
    type: string
```

I would also propose leverage a `schema` for that and reference it so generators don't generate different types for the create, read and update calls.
