### ISSUE TITLE
[👩‍💻 Documentation Request]: example of a GitHub action to load data to Object Storage

### ISSUE THREAD

**Issue by LLejoly** [scaleway/docs-content#4522]
### Summary

Right now the documentation lacks of information regarding automation process especially concerning the load and synchronisation of files with Object Storage.

### Why is it needed?

Documentation on object storage does not explain how you can automate the process and the way to use the scaleway cli is not detailed at all leading the users to find a solution by himself.

### Want to write this documentation yourself?

Yes

### Related PR(s)

#4586 

### (Optional) Scaleway Organization ID

1f10c502-9d20-44b6-9022-cffb991e6a9c

**Comment by LLejoly** [comment]
This is a draft of the procedure that could be included in the Object Storage documentation

#### 1. **Name the Workflow**
Define the name of the workflow. This name will appear in the GitHub Actions tab.

```yaml
name: Upload to Scaleway Object Storage
```

#### 2. **Trigger the Workflow**
Specify the event that triggers the workflow. In this case, it triggers on a push to the `main` branch.

```yaml
on:
  push:
    branches:
      - main
```

#### 3. **Define the Job**
Create a job named `upload` that runs on the `ubuntu-latest` environment.

```yaml
jobs:
  upload:
    environment: prd
    runs-on: ubuntu-latest
```

#### 4. **Checkout the Code**
Use the `actions/checkout@v2` action to checkout the repository code.

```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```

#### 5. **Set Up Node.js**
Set up Node.js using the `actions/setup-node@v2` action and specify the Node.js version.

```yaml
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
```

#### 6. **Install Dependencies**
Run `npm install` to install the project dependencies.

```yaml
      - name: Install dependencies
        run: npm install
```

#### 7. **Build the Website**
Run the build script to build the website.

```yaml
      - name: Build the website
        run: npm run build
```

#### 8. **Install s3cmd**
Install `s3cmd` using `apt-get`.

```yaml
      - name: Install s3cmd
        run: sudo apt-get install -y s3cmd
```

#### 9. **Install Scaleway CLI**
Use the `scaleway/action-scw@v0` action to install the Scaleway CLI.

```yaml
      - name: Install CLI
        uses: scaleway/action-scw@v0
        with:
          version: v2.37.0
```

#### 10. **Configure and Sync with Scaleway Object Storage**
Configure `s3cmd` and sync the built website to Scaleway Object Storage. Use secrets for sensitive information.

```yaml
      - run: |
          scw object config get type=s3cmd > /home/runner/.s3cfg
          s3cmd sync ./dist/* s3://your_bucket/
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
```
